server:
  error:
    include-stacktrace: on_param #configura o stacktrace
  port: 8082 #alterada porta da aplicacao

authentication:
  basic:
    username: gonini
    password: teste123
    criptografado:


spring:
  application:
    name: springboot2-essentials-feign
  datasource:
    url: jdbc:mysql://localhost:3306/teste?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #Todas as vezes que iniciar a aplicacao ira atualizar o banco
      #show-sql: true #mostra no console a query SQL que esta sendo executada pelo JPA
  output:
    ansi:
      enabled: ALWAYS #habilita os logs com fonte colorida

